# Generated by Django 4.2.16 on 2025-11-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_prescription_extra_information'),
        ('doctor', '0044_appointment_message'),
    ]

    operations = [
    ]
